# Generated by Django 3.2.9 on 2021-11-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='print',
            new_name='price',
        ),
        migrations.AddField(
            model_name='destination',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
